Portfolio
Orzala-2024/Personal-Portfolio pull request #1
Opened 2024-06-05 06:51 UTC by LimaSahibzada

🎯 This is personal portfolio to showcase my skills and experienced . Here are some feathers in my portfolio:
-  It has a sleek layout and and responsive design for all sizes.
-  Viewers can contact me through any communication apps just by clicking related icons .
-  I have added all my projects images with their real links. Just by clicking on image they can  access to my project.
- I used keyframes for animations .

This repo include below files:
-index.html
-about.html
-contact.html
-projects.html
-styles.css
-background vedio
-5 images

2024-06-06 10:16 UTC, ahzamir commented
@LimaSahibzada 

- I can not see your partner's feedback!

2024-06-06 14:11 UTC, LimaSahibzada commented
@ahzamir ,
as i mentioned in the group , my partner has told me that she is busy and won't check my project . so i submit my project. 
zuhra Hashimi is my partner.

2024-06-07 03:44 UTC, LimaSahibzada commented
@ahzamir , 
as i mentioned in the group , my partner has told me that she is busy and won't check my project . so i submit my project.
zuhra Hashimi is my partner.

2024-06-07 12:52 UTC, LimaSahibzada commented
@ahzamir ,
i just  added a media query .

2024-06-08 14:21 UTC, ahzamir requested changes
@LimaSahibzada 

- Well done lima you have done a great job implementing most of the requirements but still there are some issues on your project you need to work on
  - Chek the inline comments below
  
  - Add all of your subfiles like `about.html`, `contact.html`, `projects.html` inside a folder names /projects and then change the links to get the file from the project folder to make your project folder clean:
  
## Example:
```
  Portfolio/
  └── index.html
  └── pages/
    └── about.html
    └── projects.html
    └── contact.html
```

2024-06-08 14:21 UTC, ahzamir commented on index.html
> +    </header>
- Remove the Target blank from your page links as it is internal page links you use target blank when you want to link some external websites.

2024-06-08 14:21 UTC, ahzamir commented on index.html
> +        </div>
![Screenshot 2024-06-08 161111](https://github.com/LimaSahibzada/Personal-Portfolio/assets/96838030/36fe90ce-10bb-4392-91f8-65ba0bfd443a)

- This one is not working

2024-06-08 14:21 UTC, ahzamir commented on projects.html
- Make some changes to this page mobile version design to make it align center and justify center:
![Screenshot 2024-06-08 161018](https://github.com/LimaSahibzada/Personal-Portfolio/assets/96838030/16b9295a-0025-4fd1-bd65-763c36bc4090)

2024-06-08 17:54 UTC, LimaSahibzada commented
@ahzamir ,
I made changes in my project . kindly review it . 

thank you

2024-07-13 23:09 UTC, merged